<template>
  <v-container fluid>
    <v-col cols="12">
      <v-row align="center" justify="center">
        <v-card class="mx-auto" max-width="400">
          <v-card-text>
            <div>Web experiment with</div>
            <p class="display-1 text--primary">
              Ma•gen•ta
            </p>
            <p>
              trying to make it happen on VueJS template. Hopefully it works!
            </p>
            <div class="text--primary">
              click the play button to hear .<br />
              music generated by Neural Networks
            </div>
          </v-card-text>
          <v-card-actions>
            <v-btn text color="deep-purple accent-4" @click="play">
              Play
            </v-btn>
          </v-card-actions>
        </v-card>
      </v-row>
    </v-col>
  </v-container>
</template>
<script>
import { player, model } from "@/plugins/magenta";
export default {
  data() {
    return {
<<<<<<< HEAD
      player: new core.Player(),
=======
      //musical sequence variables to be passed to the model
      sequence: {
        ticksPerQuarter: 220,
        totalTime: 28.5,
        timeSignatures: [
          {
            time: 0,
            numerator: 4,
            denominator: 4
          }
        ],
        tempos: [
          {
            time: 0,
            qpm: 120
          }
        ],
        notes: [
          { pitch: "Gb4", startTime: 0, endTime: 1 },
          { pitch: "F4", startTime: 1, endTime: 3.5 },
          { pitch: "Ab4", startTime: 3.5, endTime: 4 },
          { pitch: "C5", startTime: 4, endTime: 4.5 },
          { pitch: "Eb5", startTime: 4.5, endTime: 5 },
          { pitch: "Gb5", startTime: 5, endTime: 6 },
          { pitch: "F5", startTime: 6, endTime: 7 },
          { pitch: "E5", startTime: 7, endTime: 8 },
          { pitch: "Eb5", startTime: 8, endTime: 8.5 },
          { pitch: "C5", startTime: 8.5, endTime: 9 },
          { pitch: "G4", startTime: 9, endTime: 11.5 },
          { pitch: "F4", startTime: 11.5, endTime: 12 },
          { pitch: "Ab4", startTime: 12, endTime: 12.5 },
          { pitch: "C5", startTime: 12.5, endTime: 13 },
          { pitch: "Eb5", startTime: 13, endTime: 14 },
          { pitch: "D5", startTime: 14, endTime: 15 },
          { pitch: "Db5", startTime: 15, endTime: 16 },
          { pitch: "C5", startTime: 16, endTime: 16.5 },
          { pitch: "F5", startTime: 16.5, endTime: 17 },
          { pitch: "F4", startTime: 17, endTime: 19.5 },
          { pitch: "G4", startTime: 19.5, endTime: 20 },
          { pitch: "Ab4", startTime: 20, endTime: 20.5 },
          { pitch: "C5", startTime: 20.5, endTime: 21 },
          { pitch: "Eb5", startTime: 21, endTime: 21.5 },
          { pitch: "C5", startTime: 21.5, endTime: 22 },
          { pitch: "Eb5", startTime: 22, endTime: 22.5 },
          { pitch: "C5", startTime: 22.5, endTime: 24.5 },
          { pitch: "Eb5", startTime: 24.5, endTime: 25.5 },
          { pitch: "G4", startTime: 25.5, endTime: 28.5 }
        ]
      },
>>>>>>> 8e5e00b011594c0dbd665c8373d6d3917945363f
      TWINKLE_TWINKLE: {
        notes: [
          { pitch: 60, startTime: 0.0, endTime: 0.5 },
          { pitch: 60, startTime: 0.5, endTime: 1.0 },
          { pitch: 67, startTime: 1.0, endTime: 1.5 },
          { pitch: 67, startTime: 1.5, endTime: 2.0 },
          { pitch: 69, startTime: 2.0, endTime: 2.5 },
          { pitch: 69, startTime: 2.5, endTime: 3.0 },
          { pitch: 67, startTime: 3.0, endTime: 4.0 },
          { pitch: 65, startTime: 4.0, endTime: 4.5 },
          { pitch: 65, startTime: 4.5, endTime: 5.0 },
          { pitch: 64, startTime: 5.0, endTime: 5.5 },
          { pitch: 64, startTime: 5.5, endTime: 6.0 },
          { pitch: 62, startTime: 6.0, endTime: 6.5 },
          { pitch: 62, startTime: 6.5, endTime: 7.0 },
          { pitch: 60, startTime: 7.0, endTime: 8.0 }
        ],
        tempos: [
          {
            time: 0,
            qpm: 120
          }
        ],
        totalTime: 8
      }
    };
  },
  methods: {
    play() {
<<<<<<< HEAD
      const globalAny = global;
      globalAny.performance = Date;
      globalAny.fetch = require("node-fetch");

      //const player = new core.Player();
    },
    twinkle() {
      this.player.start(this.TWINKLE_TWINKLE);
=======
      model
        .initialize()
        .then(() => model.sample(1))
        .then(samples => {
          player.resumeContext();
          player.start(samples[0]);
        });
    },
    twinkle() {
      player.start(this.TWINKLE_TWINKLE);
      player.stop();
>>>>>>> 8e5e00b011594c0dbd665c8373d6d3917945363f
    }
  }
};
</script>
